apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fastfood
data:
  NODE_ENV: "production"
  PORT: "3000"
  DYNAMODB_CLIENTS_TABLE: ""
  DYNAMODB_PRODUCTS_TABLE: ""
  DYNAMODB_ORDERS_TABLE: ""
  AUTH_API_URL: ""
  AWS_REGION: "us-east-1"
