---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynamodb-access
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fastfood-dynamodb-access
  namespace: fastfood
subjects:
- kind: ServiceAccount
  name: fastfood-app
  namespace: fastfood
roleRef:
  kind: ClusterRole
  name: dynamodb-access
  apiGroup: rbac.authorization.k8s.io
