apiVersion: v1
kind: Service
metadata:
  name: fastfood-service
  namespace: fastfood
spec:
  selector:
    app: fastfood
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP