# kubernetes-app/k8s/pagamentos/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos
  namespace: pagamentos
  labels:
    app: pagamentos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamentos
  template:
    metadata:
      labels:
        app: pagamentos
    spec:
      containers:
      - name: pagamentos
        image: fastfood/pagamentos:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: auth-endpoint
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10