# kubernetes-app/k8s/pagamentos/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pagamentos
  namespace: pagamentos
spec:
  selector:
    app: pagamentos
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP