# kubernetes-infra/kubernetes/config/app-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fastfood
type: Opaque
data:
  # Estes valores estão codificados em base64 
  # Para produção, use um gerenciador de segredos como AWS Secrets Manager ou HashiCorp Vault
  JWT_SECRET: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="  # change-me-in-production
  MERCADO_PAGO_ACCESS_TOKEN: "VEVTVC0xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkw"
  AWS_ACCESS_KEY_ID: "QUtJQVhYWFhYWFhYWFhYWFhYWA=="
  AWS_SECRET_ACCESS_KEY: "eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eA=="