# kubernetes-app/k8s/services/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fastfood-api
  namespace: fastfood
  labels:
    app: fastfood-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: fastfood-api