apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
    </source>
    
    <match kubernetes.**>
      @type cloudwatch_logs
      log_group_name /k8s/fastfood/application
      region us-east-1
    </match>
