apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fastfood
data:
  NODE_ENV: "production"
  PORT: "3000"
  AWS_REGION: "us-east-1"
  CORS_ALLOWED_ORIGINS: "*"
  LOG_LEVEL: "info"
