apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fastfood
type: Opaque
stringData:
  AWS_REGION: "us-east-1"
  AUTH_LAMBDA: "fastfood-auth"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-endpoints
  namespace: fastfood
type: Opaque
stringData:
  auth-endpoint: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/fastfood-auth/invocations"