# Service Accounts para Fast Food app com IRSA
# Tech Challenge Fase 3
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastfood-app
  namespace: fastfood
  annotations:
    eks.amazonaws.com/role-arn: ${DYNAMODB_ROLE_ARN}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastfood-secrets
  namespace: fastfood
  annotations:
    eks.amazonaws.com/role-arn: ${SECRETS_ROLE_ARN}
