# kubernetes-app/k8s/pedidos/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pedidos
  namespace: pedidos
spec:
  selector:
    app: pedidos
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP