# .github/workflows/integration-tests.yml
name: Integration Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Diariamente à meia-noite

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Verificar existência do cluster EKS
        id: check-cluster
        run: |
          if aws eks describe-cluster --name fastfood-dev --region us-east-1 &>/dev/null; then
            echo "O cluster fastfood-dev existe. Prosseguindo com os testes."
            echo "cluster_exists=true" >> $GITHUB_OUTPUT
          else
            echo "O cluster fastfood-dev não está criado."
            echo "cluster_exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Configure kubectl
        if: steps.check-cluster.outputs.cluster_exists == 'true'
        run: |
          aws eks update-kubeconfig --name fastfood-dev --region us-east-1
      
      - name: Run integration tests
        if: steps.check-cluster.outputs.cluster_exists == 'true'
        run: ./run-integration-tests.sh